
spring:
  application:
    name: jpa-tesing-api

  datasource:
    username: chantha
    password: 123
    url: jdbc:postgresql://110.74.194.123:5432/chanthaDB
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 9090